### ISSUE TITLE
Blatt 2 Aufgabe 6

### ISSUE THREAD

**Issue by benny1611** [sweIhm-ws2018-19/skillproject-fr-21#10]
In Bearbeitung 😃

**Comment by benny1611** [comment]
Bitte prüfen und Bescheid geben damit ich den Issue schließen kann. Danke!

**Comment by Tengoru** [comment]
Sehe kein Problem ! sollte so passen oder was meint ihr?

**Comment by xela1601** [comment]
sieht soweit gut aus. Was mich noch stört ist, dass die Beschreibungen  auf den Pfeilen teilweise so lang sind, dass sie nicht vollständig angezeigt werden. Kann man das noch fixen?

**Comment by benny1611** [comment]
Ohh ja, da hast du Recht. Ich mach's wieder gut und lade es hoch

**Comment by benny1611** [comment]
Fertig! Schau mal jetzt und sag ob alles gut ist.

**Comment by mas7erpi3ce** [comment]
Ich kann keine Fehler erkennen. Meiner Meinung nach können wir dieses issue schließen

**Comment by xela1601** [comment]
Jetzt sieht alles gut aus! Benni kannst den Issue schließen! Gute Arbeit!
