### ISSUE TITLE
Blatt 2 Aufgabe 8

### ISSUE THREAD

**Issue by benny1611** [sweIhm-ws2018-19/skillproject-fr-21#11]
Mache gerade Aufgabe 8. Ich gebe euch bescheid sobald ich fertig bin

**Comment by Tengoru** [comment]
Sieht gut aus! Sollte meiner Meinung nach stimmen :D

**Comment by mas7erpi3ce** [comment]
Die Kästchen sind manchmal zu klein -> Teil des Wortes wird angeschnitten. Siehe Dokument

**Comment by benny1611** [comment]
Super. Danke dir!
