### ISSUE TITLE
Aufgabe 9 wird bearbeitet ...

### ISSUE THREAD

**Issue by Tengoru** [sweIhm-ws2018-19/skillproject-fr-21#12]
mache jetzt aufgabe 9 bitte anschauen wenn es oben ist !!

**Comment by Tengoru** [comment]
so ist hochgeladen bitte kommentieren!!

**Comment by benny1611** [comment]
Sieht gut aus :ok_hand: :kiss:

**Comment by xela1601** [comment]
gefällt mir noch nicht. Die eine Beschriftung des Pfeiles mit "drucken()" fehlt.
Außerdem wird die Antwort der drucken()-methoden in Form des bool-Wertes nirgends aufgeführt.
Bitte noch überarbeiten!
