### ISSUE TITLE
Github Wiki Seite für Übungsblatt 2

### ISSUE THREAD

**Issue by Tengoru** [sweIhm-ws2018-19/skillproject-fr-21#7]
Bitte sobald vollständig anschauen und kommentieren !!!

**Comment by xela1601** [comment]
habe das wiki nochmal überarbeitet.
Insofern jetzt alle dateien richtig benannt sind und im richtigen Ordner, werden die Lösungen automatisch im wiki auftauchen.
unsere Konvention: aufgabex_loesung.png oder aufgabex_angabe.png
hierbei x durch die entsprechende Zahl ersetzen.

**Comment by xela1601** [comment]
habe noch ein Inhaltsverzeichnis hinzugefügt, das einem erlaubt einfacher zu den einzelnen Aufgaben zu kommen ohne so lange runter zu scrollen.

**Comment by Tengoru** [comment]
Aye aye danke dir :D
