### ISSUE TITLE
Übungsblatt 2 Aufgabe 3 in Bearbeitung 

### ISSUE THREAD

**Issue by Tengoru** [sweIhm-ws2018-19/skillproject-fr-21#8]
Bin mit Aufgabe 1 fertig und lade sie hoch. Mache bei Aufgabe 3 weiter.

**Comment by Tengoru** [comment]
Aufgabe 3 fettig und hochgeladen bitte anschauen.

**Comment by benny1611** [comment]
Super weiter so 💋

**Comment by Tengoru** [comment]
Dankeee   💋

**Comment by xela1601** [comment]
Gute Arbeit !  Sieht gut aus.

**Comment by mas7erpi3ce** [comment]
Gute Arbeit! Nur noch eine kleine Sache. Die Source Datei befolg nicht unsere naming conventions. Bitte um Umbenennung. Danach kann dieses issue geschlossen werden
